[package]
name = "recv_spi_buffer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "recv_spi_buffer"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
spidev = "0.6.0"
